controllers/DefaultController.php
<?php

namespace common\modules\keyContent\controllers;

use common\helpers\ArrayHelper;
use common\modules\keyContent\models\Category;
use common\modules\keyContent\models\Article;
use common\modules\keyContent\models\Access;
use common\modules\keyContent\models\ArticleCategory;
use common\modules\keyContent\models\Commenting;
use common\modules\keyContent\models\ContentLang;
use common\modules\keyContent\models\ContentState;
use common\modules\keyContent\models\ContentVersion;
use common\modules\keyContent\models\ContentVersions;
use common\modules\keyContent\models\Lang;
use common\modules\keyContent\models\Langrrs;
use common\modules\keyContent\models\Langs;
use common\modules\keyContent\models\search\ArticleSearch;
use common\modules\keyContent\models\State;
use common\modules\keyContent\models\Tag;
use common\modules\keyRbac\models\Roles;
use common\modules\keyStaff\models\Staff;
use Yii;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use function compact;

class DefaultController extends \common\controllers\BaseController
{
    public $_enabledActions = [
        'index',
        'create',
        'update'
    ];

    public $_model = Article::class;

    public $_searchModel = ArticleSearch::class;

    public $_searchModelName = 'ArticleSearch';

    public $_searchKey = 'article_search';

    public function actionIndex($params = [])
    {
        return parent::actionIndex($params); // TODO: Change the autogenerated stub
    }

    /**
     * Updates an existing Positions model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws ForbiddenHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $categoriesObjArr = Category::find()->where("id > 0")->all();
        $categories = ArrayHelper::map($categoriesObjArr, 'id', 'title.' . Yii::$app->language);

        $articleCategoriesArr = Article::find()->where(['id' => $model->id])->one()->getCategories()->asArray()->all();
        $articleCategories = [];
        foreach ($articleCategoriesArr as $item) {
            $articleCategories[$item['id']] = (int)$item['id'];
        }

        $statesObjArr = State::find()->where("id > 0")->all();
        $states = ArrayHelper::map($statesObjArr, 'id', 'title.' . Yii::$app->language);
        $articleState = $model->state;

        $accessObjArr = Access::find()->where("id > 0")->all();
        $accesses = ArrayHelper::map($accessObjArr, 'id', 'title.' . Yii::$app->language);
        $articleAccess = $model->access;

        $langsObjArr = Lang::find()->where("id > 0")->all();
        $langs = ArrayHelper::map($langsObjArr, 'id', 'title.' . Yii::$app->language);
        $articleLang = $model->lang;

        $tags = Tag::getTags();

        $articleTagsArr = Article::find()->where(['id' => $model->id])->one()->getTags()->asArray()->all();
        $articleTags = [];
        foreach ($articleTagsArr as $item) {
            $articleTags[$item['id']] = (int)$item['id'];
        }

        $authorsObjArr = Staff::findBySql('SELECT staff_id, username FROM staff')->asArray()->all();
        $authors = [];
        foreach ($authorsObjArr as $item) {
            $authors[$item['staff_id']] = $item['username'];
        }
        $articleAuthor = $model->created_by;

        $commentingsObjArr = Commenting::find()->where("id < 2")->all();
        $commentings = ArrayHelper::map($commentingsObjArr, 'id', 'title.' . Yii::$app->language);
        $articleCommenting = $model->commenting;

        $post = Yii::$app->request->post();
        if ($model->load($post))
        {
            if ($model->save(false))
                return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->renderTmpl('update', compact(
            'model', 'categories', 'articleCategories', 'states', 'articleState', 'accesses', 'articleAccess',
            'langs', 'articleLang', 'authors', 'articleAuthor', 'tags', 'articleTags', 'commentings', 'articleCommenting'));
    }

    public function actionCreate()
    {
        $model = new Article();

        $categoriesObjArr = Category::find()->where("id > 0")->all();
        $categories = ArrayHelper::map($categoriesObjArr, 'id', 'title.' . Yii::$app->language);

        $articleCategories = [];

        $statesObjArr = State::find()->where("id > 0")->all();
        $states = ArrayHelper::map($statesObjArr, 'id', 'title.' . Yii::$app->language);
        $articleState = $model->state;

        $accessObjArr = Access::find()->where("id > 0")->all();
        $accesses = ArrayHelper::map($accessObjArr, 'id', 'title.' . Yii::$app->language);
        $articleAccess = $model->access;

        $langsObjArr = Lang::find()->where("id > 0")->all();
        $langs = ArrayHelper::map($langsObjArr, 'id', 'title.' . Yii::$app->language);
        $articleLang = $model->lang;

        $authorsObjArr = Staff::findBySql('SELECT staff_id, username FROM staff')->asArray()->all();
        $authors = [];
        foreach ($authorsObjArr as $item) {
            $authors[$item['staff_id']] = $item['username'];
        }
        $articleAuthor = null;

        $tags = Tag::getTags();
        $articleTags = [];

        $commentingsObjArr = Commenting::find()->where("id < 2")->all();
        $commentings = ArrayHelper::map($commentingsObjArr, 'id', 'title.' . Yii::$app->language);
        $articleCommenting = null;

        $post = Yii::$app->request->post();
        if ($model->load($post))
        {
            if ($model->save(false))
                return $this->redirect(['update', 'id' => $model->id]);
        }

        $post = Yii::$app->request->post();
        if ($model->load($post))
        {
            if ($model->save(false))
                return $this->redirect(['index']);
        }


        return $this->renderTmpl('update', compact('model', 'categories', 'articleCategories', 'states', 'articleState', 'accesses', 'articleAccess',
            'langs', 'articleLang', 'authors', 'articleAuthor', 'tags', 'articleTags', 'commentings', 'articleCommenting'));
    }

    private function updateCategories($model, $oldCategories = [])
    {
        if (isset($_POST['categories'])) {
            $newCategories = array_flip($_POST['categories']);

            $itemsToDelete = array_diff_key($oldCategories, $newCategories);
            if (!empty($itemsToDelete)) {
                foreach ($itemsToDelete as $key => $val) {
                    $contentCategory = ArticleCategory::findOne(['content_id' => $model->id, 'category_id' => $key]);
                    $contentCategory->delete();
                }
            }

            $itemsToInsert = array_diff_key($newCategories, $oldCategories);
            if (!empty($itemsToInsert)) {
                foreach ($itemsToInsert as $key => $val) {
                    $contentCategory = new ArticleCategory();
                    $contentCategory->setAttributes(['content_id' => $model->id, 'category_id' => $key]);
                    $contentCategory->save();
                }
            }

            return true;
        }

        $contentCategories = ArticleCategory::findAll(['content_id' => $model->id]);
        foreach ($contentCategories as $contentCategory) {
            $contentCategory->delete();
        }
    }

    private function createContentVersion(Article $content)
    {
        $version = new ContentVersions();

        $version->setAttribute('categories', $_POST['categories']);
        $version->setAttribute('content_id', $content->getAttribute('id'));

        $version->setAttributes($content->attributes);

        $version->save();
    }
}

controllers/VersionController.php
<?php

namespace common\modules\keyContent\controllers;


use common\controllers\BaseController;
use common\helpers\ArrayHelper;
use common\modules\keyContent\models\Category;
use common\modules\keyContent\models\Article;
use common\modules\keyContent\models\Tag;
use common\modules\keyContent\models\Version;
use Yii;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Controller;

class VersionController extends Controller
{


    public function actionIndex($id)
    {
        return $this->render('index', [
            'id' => $id,
        ]);
    }

    public function actionView($id)
    {
        $model = Version::findOne($id);

        $versionCategoriesStr = implode(',' , $model->getAttribute('categories'));
        $categoriesObjArr = Category::find()->where("id IN (" . $versionCategoriesStr . ")")->all();
        $categories = ArrayHelper::map($categoriesObjArr, 'id', 'title.' . Yii::$app->language);

        $versionTagsStr = implode(',' , $model->getAttribute('tags'));
        $tagsObjArr = Tag::find()->where("id IN (" . $versionTagsStr . ")")->all();
        $tags = ArrayHelper::map($tagsObjArr, 'id', 'title.' . Yii::$app->language);

        $post = Yii::$app->request->post();
        if ($model->load($post)) {
            $versionAttributes = $model->getAttributes();
            unset($versionAttributes['categories']);
            unset($versionAttributes['tags']);

            if ($versionAttributes['text'] === null) {
                $prevText = Version::findBySql('
                    SELECT `text` from content_version where id = (SELECT max(id) FROM content_version where `text` IS NOT NULL AND id < ' .
                    $model->id . ')')->one()->getAttribute('text');

                $versionAttributes['text'] = $prevText;
            }

            $content = Article::findOne($model->getAttribute('article_id'));
            $content->setAttributes($versionAttributes);

            if ($content->save(false))
                return $this->redirect(['default/update', 'id' => $model->getAttribute('article_id')]);
        }

        return $this->render('view', [
            'model' => $model,
            'categories' => $categories,
            'tags' => $tags
        ]);
    }
}

views/default/_form.php
<?php

use dosamigos\ckeditor\CKEditor;
use yii\helpers\Html;
use common\widgets\ActiveForm;
use common\modules\keyAccess\widgets\TagsinputWidget;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model common\modules\keyContent\models\Article */
/* @var $form common\widgets\ActiveForm */

use kartik\file\FileInput;

$form = ActiveForm::begin([
    'id' => 'article_form',
    'options' => [
        'style' => 'display: contents;'
    ]
]);

?>

<?php

    if($model->isNewRecord){
        $this->params['buttons'] .= Html::submitButton(Yii::t('staff', 'BUTTON_SAVE'), ['class' => 'btn btn-success cr_cont', 'form' => 'article_form']);
    }
    else {
        $this->params['buttons'] .= Html::submitButton(Yii::t('staff', 'BUTTON_UPDATE'), ['class' => 'btn btn-success cr_cont', 'form' => 'article_form']);

    }

?>

<div class="col-lg-6">
    <?= $form->field($model, 'title')->textInput() ?>
</div>
<div class="col-lg-2">
    <?= $form->field($model, 'alias')->textInput() ?>
</div>
<div class="col-lg-4"></div>

        <div class="col-lg-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#materials" role="tab" aria-controls="home" aria-selected="true">Материал</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Изображения и ссылки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="messages-tab" data-toggle="tab" href="#messages" role="tab" aria-controls="messages" aria-selected="false">Публикация</a>
                </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content body" style="padding: 15px;background-color:#fff;">

                <!-- material block begin -->
                <div class="tab-pane active" id="materials" role="tabpanel" aria-labelledby="home-tab">
                    <div class="d-flex">
                        <div class="material-text w-75">
                            <?= $form->field($model, 'text')->widget(CKEditor::className(), [
                                'options' => ['rows' => 6, 'cols' => 500, 'id' => 'editor2'],
                                'preset' => 'full',
                                'clientOptions' => [
                                    'filebrowserBrowseUrl' => '/finder/index',
                                ]
                            ]); ?>
                        </div>
                        <div class="material-rside w-25 pl-3">
                            <div class="material-categories">
                                <?= '<label class="control-label pt2">Категории</label>'; ?>
                                <?= Select2::widget([
                                    'name' => 'categories',
                                    'value' => $articleCategories,
                                    'data' => $categories,
                                    'options' => [
                                        'multiple' => true,
                                        'placeholder' => Yii::t('staff', 'MODEL_STAFF_POSITION_PLACEHOLDER'),
                                        'required' => true
                                    ],
                                    'pluginOptions' => [
                                        'width' => '100%'
                                    ],
                                ]); ?>
                            </div>
                            <div class="material-state">
                                <?= '<label class="control-label pt-2">Состояние</label>'; ?>
                                <?= Select2::widget([
                                    'name' => 'state',
                                    'value' => $articleState,
                                    'data' => $states,
                                    'options' => [
                                        'multiple' => false,
                                        'placeholder' => Yii::t('staff', 'MODEL_STAFF_POSITION_PLACEHOLDER'),
                                        'required' => true
                                    ],
                                    'pluginOptions' => [
                                        'width' => '100%'
                                    ],
                                ]); ?>
                            </div>
                            <div class="material-state">
                                <?= '<label class="control-label pt-2">Доступ</label>'; ?>
                                <?= Select2::widget([
                                    'name' => 'access',
                                    'value' => $articleAccess,
                                    'data' => $accesses,
                                    'options' => [
                                        'multiple' => false,
                                        'placeholder' => Yii::t('staff', 'MODEL_STAFF_POSITION_PLACEHOLDER'),
                                        'required' => true
                                    ],
                                    'pluginOptions' => [
                                        'width' => '100%'
                                    ],
                                ]); ?>
                            </div>
                            <div class="material-lang">
                                <?= '<label class="control-label pt-2">Язык</label>'; ?>
                                <?= Select2::widget([
                                    'name' => 'lang',
                                    'value' => $articleLang,
                                    'data' => $langs,
                                    'options' => [
                                        'multiple' => false,
                                        'placeholder' => 'language',//Yii::t('staff', 'MODEL_STAFF_POSITION_PLACEHOLDER'),
                                        'required' => true
                                    ],
                                    'pluginOptions' => [
                                        'width' => '100%'
                                    ],
                                ]); ?>
                            </div>
                            <div class="material-categories">
                                <?= '<label class="control-label pt2">Метки</label>'; ?>
                                <?= Select2::widget([
                                    'name' => 'tags',
                                    'value' => $articleTags,
                                    'data' => $tags,
                                    'options' => [
                                        'multiple' => true,
                                        'placeholder' => 'метки',
                                        'required' => true
                                    ],
                                    'pluginOptions' => [
                                        'width' => '100%'
                                    ],
                                ]); ?>

                                <?= $form->field($model, 'tags')->widget(TagsinputWidget::classname(), [
                            'clientOptions' => [
                                'trimValue' => true,
                                'allowDuplicates' => false
                            ]
                        ]) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- material block end -->

                <!-- images block start-->
                <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <div class="d-flex">
                        <?= '<label class="control-label">Изображение для вступительного текста материала</label>'; ?>
                        <?= $form->field($model, 'image1')->widget(FileInput::classname(), [
                            'options' => ['accept' => 'image/*'],
                        ]);
                        ?>
                    </div>
                </div>
                <!-- images block end-->

                <!-- publish block start -->
                <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab">
                    <div class="row d-flex">
                        <div class="publish-lside col-lg-3 pl-3">
                            <?php
                                $createdAt = '';
                                if ($model->getAttribute('created_at') !== null) {
                                    $createdAt = date("d-m-Y  h:i:s", $model->getAttribute('created_at'));
                                }
                            ?>
                            <?= '<label class="control-label pt-2">Дата создания</label>'; ?>
                            <?= \kartik\datetime\DateTimePicker::widget([
                                'name' => 'created_at',
                                'type' => \kartik\datetime\DateTimePicker::TYPE_COMPONENT_APPEND,
                                'value' => $createdAt,
                                'pluginOptions' => [
                                'autoclose'=>true,
                                'format' => 'dd-mm-yyyy hh:ii:ss'
                            ]
                            ]);
                            ?>

                            <?php
                                $publishedAt = '';
                                if ($model->getAttribute('published_at') !== null) {
                                    $publishedAt = date("d-m-Y  h:i:s", $model->getAttribute('published_at'));
                                }
                            ?>
                            <?= '<label class="control-label pt-2">Дата публикации</label>'; ?>
                            <?= \kartik\datetime\DateTimePicker::widget([
                                'name' => 'published_at',
                                'type' => \kartik\datetime\DateTimePicker::TYPE_COMPONENT_APPEND,
                                'value' => $publishedAt,
                                'pluginOptions' => [
                                    'autoclose'=>true,
                                    'format' => 'dd-mm-yyyy hh:ii:ss'
                                ]
                            ]);
                            ?>

                            <?php if(!$model->isNewRecord): ?>
                                <?= '<label class="control-label pt-2">Автор</label>'; ?>
                                <?= Select2::widget([
                                    'name' => 'created_by',
                                    'value' => $articleAuthor,
                                    'data' => $authors,
                                    'options' => [
                                        'multiple' => false,
                                        'placeholder' => 'author',//Yii::t('staff', 'MODEL_STAFF_POSITION_PLACEHOLDER'),
                                        'required' => true
                                    ],
                                    'pluginOptions' => [
                                        'width' => '100%'
                                    ],
                                ]); ?>
                                <label class="control-label pt-2">Изменено пользователем:</label>
                                <input type="text" disabled="disabled" class="form-control" value="<?= $authors[$model->getAttribute('updated_by')]; ?>" />
                            <?php endif; ?>

                            <?php
                            $updatedAt = '';
                            if ($model->getAttribute('updated_at') !== null): ?>
                                <?php $updatedAt = date("d-m-Y  h:i:s", $model->getAttribute('updated_at')); ?>

                                <?= '<label class="control-label pt-2">Дата изменения</label>'; ?>
                                <input type="text" disabled="disabled" class="form-control" value="<?= $updatedAt; ?>" />
                            <?php endif; ?>

                        </div>
                        <div class="col-lg-3"></div>
                        <div class="publish-rside col-lg-3 order-lg-2 pl-3">
                            <?= $form->field($model, 'meta_title')->textInput()->label('Meta-title'); ?>
                            <?= $form->field($model, 'meta_desc')->textInput()->label('Meta-description'); ?>

                            <?= '<label class="control-label pt-2">Комментирование</label>'; ?>
                            <?= Select2::widget([
                                'name' => 'commenting',
                                'value' => $articleCommenting,
                                'data' => $commentings,
                                'options' => [
                                    'multiple' => false,
                                    'placeholder' => 'комментирование',//Yii::t('staff', 'MODEL_STAFF_POSITION_PLACEHOLDER'),
                                    'required' => true
                                ],
                                'pluginOptions' => [
                                    'width' => '100%'
                                ],
                            ]); ?>

                        </div>
                    </div>
                </div>
                <!-- publish block end-->
            </div>
        </div>

<?php ActiveForm::end(); ?>

views/default/create.php
<?php

/* @var $this yii\web\View */
/* @var $model common\modules\keyContent\models\Article */

$this->title = Yii::t('staff','CREATE_EMPLOYEE');
$this->params['breadcrumbs'][] = ['label' => Yii::t('staff','STAFF'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?= $this->render('_form', compact(
    'model', 'categories', 'articleCategories', 'states', 'articleState', 'accesses', 'articleAccess',
    'langs', 'articleLang', 'authors', 'articleAuthor', 'tags', 'articleTags', 'commentings', 'articleCommenting'
)) ?>

views/default/index.php
<?php

use yii\helpers\Html;
use common\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\modules\keyStaff\models\search\StaffSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = \Yii::t('staff', 'STAFF');
$this->params['breadcrumbs'][] = $this->title;
$this->params['buttons'] = Html::a(Yii::t('staff', 'BUTTON_CREATE_EMPLOYEE'), ['/keyContent/default/create'], ['class' => 'btn btn-success white-btn cr_cont']);
?>

<div class="col-lg-12">
    <div class="card ">
        <?php \yii\widgets\Pjax::begin([
            'id' => 'staffGridView',
            'enablePushState' => false,
        ]);
        ?>
            <div class="header">
                <div class="search_tables">
                    <?= Html::beginForm(['/keyStaff/default/index'],'get', ['data-pjax' => 1]); ?>
                        <input name="StaffSearch[searchAll]" class="form-control search_field" placeholder="<?= \Yii::t('crm', 'SEARCH_PLACEHOLDER') ?>" type="text" value="<?= \common\helpers\FilterHelper::getSearchValue('Staff', 'Staff', 'searchAll') ?>">
                        <?= Html::submitButton('<i class="icon-magnifier"></i> '. \Yii::t('crm', 'BTN_SEARCH'), [
                            'class' => 'btn btn-outline-success'
                        ]) ?>
                        <button type="button" class="btn btn-outline-info showFilters"><?= \Yii::t('crm', 'BTN_FILTER') ?></button>
                    <?= Html::endForm();?>

                    <?= Html::a(\Yii::t('crm', 'BTN_CLEAR'), \yii\helpers\Url::to(['/keyContent/default/index']), [
                        'class' => 'btn btn-outline-secondary',
                        'data-pjax' => 1,
                        'data-method' => 'POST',
                        'data-params' => [
                            'StaffSearch[clear]' => 1
                        ]
                    ]) ?>
                </div>
            </div>
            <div class="body">
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'gridPjaxID' => 'staffGridView',
                    'filterRowOptions' => [
                        'class' => (\common\helpers\FilterHelper::getFilterClass('Content', 'Content')) ? 'filters show_filters' : 'filters hide_filters'
                    ],
                    'rowOptions' => function ($model, $key, $index, $grid){
                        return [
                            'role' => 'row',
                            'class' => ($index % 2) ? 'odd' : 'even'
                        ];
                    },
                    'columns' => \common\modules\keyContent\helpers\ContentColumnHelper::getColumns($searchModel),
                ]); ?>

            </div>
        <?php \yii\widgets\Pjax::end(); ?>

        <?php \yii\widgets\Pjax::begin(['id' => 'bulkPjax', 'enablePushState' => false]); ?>
            <?= \common\widgets\BulkFormWidget::widget(['url' => '/keyStaff/default/index']) ?>
        <?php \yii\widgets\Pjax::end(); ?>
    </div>
</div>

<?php \common\widgets\BulkWidget::registerJS($this, 'staffGridView'); ?>

views/default/update.php
<?php

/* @var $this yii\web\View */
/* @var $model common\modules\keyContent\models\Article */

$this->title = Yii::t('staff','UPDATE_EMPLOYEE');
$this->params['breadcrumbs'][] = ['label' => Yii::t('staff','STAFF'), 'url' => ['versionsList']];
$this->params['breadcrumbs'][] = $model->title;
?>

<?= $this->render('_form', compact(
    'model', 'categories', 'articleCategories', 'states', 'articleState', 'accesses', 'articleAccess',
            'langs', 'articleLang', 'authors', 'articleAuthor', 'tags', 'articleTags', 'commentings', 'articleCommenting'
)) ?>


<?php

if(!$model->isNewRecord){
    $this->params['buttons'] .= yii\helpers\Html::a('Версии', \yii\helpers\Url::to(['version/index', 'id' => $model->id]), [
        'class' => 'btn btn-secondary profile_actions',
        'title' => 'Версии',
    ]);
}

?>